language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g karma-cli
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - grunt

script:
  - karma start --no-auto-watch --single-run --browsers Firefox

after_success:
  cat out/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
