language: node_js
node_js:
  - 0.10.45

before_install:
  - npm install -g karma-cli
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm prune && npm install
  - bower prune && bower install
  - grunt

script:
  - npm test

after_success:
  cat out/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  directories:
    - node_modules
    - bower_components
  